#!/bin/bash
if [ $# -ne 4 ];then
	echo "Usage:"
        echo "      `basename $0` -p password -a controller_address"
	exit 0
fi
while getopts 'p:a:' OPT; do
case $OPT in
        p)
            PASSWORD="$OPTARG";;
	a)
	    CTRL_ADDRESS="$OPTARG";;
        ?)
            echo "Usage:"
            echo "      `basename $0` -p password"
	    exit 0
esac
done

TOP_DIR=$(cd $(dirname "$0") && pwd)

#get available space
cd $TOP_DIR
size=$(sudo df -m|grep '/$'|awk '{print $4}')
t_size=$[size/1024-400]
if [ $t_size  ]
back_file_size=$[size/1024-400]

#install openstack
FIXED_RANGE=10.0.0.0/20
FLOATING_RANGE=192.168.136.1/24
cd $TOP_DIR
cd devstack
sudo killall screen
cat <<EOF >localrc
FLAT_INTERFACE=eth0
FIXED_RANGE=$FIXED_RANGE
FIXED_NETWORK_SIZE=4096
FLOATING_RANGE=$FLOATING_RANGE
MULTI_HOST=1
MYSQL_PASSWORD=$PASSWORD
RABBIT_PASSWORD=$PASSWORD
SERVICE_PASSWORD=$PASSWORD
ADMIN_PASSWORD=$PASSWORD
SERVICE_TOKEN=$PASSWORD
VOLUME_BACKING_FILE_SIZE=$back_file_size
MULTI_HOST=1
MYSQL_HOST=$CTRL_ADDRESS
RABBIT_HOST=$CTRL_ADDRESS
GLANCE_HOSTPORT=${CTRL_ADDRESS}:9292
ENABLED_SERVICES=n-cpu,n-net,n-api,n-novnc,cinder,c-vol
EOF
./stack.sh

#determine IP infor
cd $TOP_DIR
. devstack/functions
HOST_IP_IFACE=${HOST_IP_IFACE:-$(ip route | sed -n '/^default/{ s/.*dev \(\w\+\)\s\+.*/\1/; p; }')}
HOST_IP=""
HOST_IPS=`LC_ALL=C ip -f inet addr show ${HOST_IP_IFACE} | awk '/inet/ {split($2,parts,"/");  print parts[1]}'`
for IP in $HOST_IPS; do
        if ! (address_in_net $IP $FIXED_RANGE || address_in_net $IP $FLOATING_RANGE); then
            HOST_IP=$IP
            break;
        fi
    done
    if [ "$HOST_IP" == "" ]; then
        echo "Could not determine host ip address."
        exit 1
fi

#install monitor related package and start services
cd $TOP_DIR
cd kanyun/
cat <<EOF >kanyun.conf
[worker]
id: worker_$(hostname)
worker_timeout: 60
dataserver_host: $CTRL_ADDRESS
dataserver_port: 5551
log: /tmp/kanyun-worker.log
EOF
sudo ps ax|grep -v grep|grep kanyun-|awk '{print $1}'|xargs -L 1 kill -9
sudo apt-get -y install libzmq-dev python-setuptools python-mysqldb redis-server python-redis python-zmq
nohup ./kanyun-worker >.kanyun-worker.nohup &
cd ..
