#!/bin/bash
TOP_DIR=$(cd $(dirname "$0") && pwd)

if [ $# -ne 2 ];then
	echo "Usage:"
        echo "      `basename $0` -p password"
	exit 0
fi
while getopts 'p:' OPT; do
case $OPT in
        p)
            PASSWORD="$OPTARG";;
        ?)
            echo "Usage:"
            echo "      `basename $0` -p password"
	    exit 0
esac
done


#install captcha
cd $TOP_DIR
cd django-simple-captcha-0.3.0
sudo python setup.py install

#determine IP infor
cd $TOP_DIR
. devstack/functions
HOST_IP_IFACE=${HOST_IP_IFACE:-$(ip route | sed -n '/^default/{ s/.*dev \(\w\+\)\s\+.*/\1/; p; }')}
HOST_IP=""
HOST_IPS=`LC_ALL=C ip -f inet addr show ${HOST_IP_IFACE} | awk '/inet/ {split($2,parts,"/");  print parts[1]}'`
for IP in $HOST_IPS; do
        if ! (address_in_net $IP $FIXED_RANGE || address_in_net $IP $FLOATING_RANGE); then
            HOST_IP=$IP
            break;
        fi
    done
    if [ "$HOST_IP" == "" ]; then
        echo "Could not determine host ip address."
        exit 1
fi

#install monitor related package and start services
cd $TOP_DIR
cd kanyun/
cat <<EOF >kanyun.conf
[server]
host: *
port: 5551

[mysql_db]
host:127.0.0.1
user:root
passwd:$PASSWORD
db:monitor
cache_server:localhost
cache_time_buffer:144000

[worker]
id: worker_$(hostname)
worker_timeout: 60
dataserver_host: 127.0.0.1
dataserver_port: 5551
log: /tmp/kanyun-worker.log
EOF
sudo ps ax|grep -v grep|grep kanyun-|awk '{print $1}'|xargs -L 1 kill -9
sudo apt-get -y install libzmq-dev python-setuptools python-mysqldb redis-server python-redis python-zmq
nohup ./kanyun-server > .kanyun-server.nohup&
nohup ./kanyun-worker >.kanyun-worker.nohup &
cd ..

#get available space
cd $TOP_DIR
size=$(sudo df -m|grep '/$'|awk '{print $4}')
back_file_size=$[size/1024]

#install openstack
FIXED_RANGE=10.0.0.0/20
FLOATING_RANGE=192.168.136.1/24
cd $TOP_DIR
cd devstack
sudo killall screen
cat <<EOF >localrc
FLAT_INTERFACE=eth0
FIXED_RANGE=$FIXED_RANGE
FIXED_NETWORK_SIZE=4096
FLOATING_RANGE=$FLOATING_RANGE
MULTI_HOST=1
MYSQL_PASSWORD=csdb123cnic
RABBIT_PASSWORD=$PASSWORD
SERVICE_PASSWORD=$PASSWORD
ADMIN_PASSWORD=$PASSWORD
SERVICE_TOKEN=$PASSWORD
ENABLED_SERVICES=g-api,g-reg,key,n-api,n-crt,n-obj,n-cpu,n-net,cinder,c-sch,c-api,c-vol,n-sch,n-novnc,n-xvnc,n-cauth,horizon,mysql,rabbit
VOLUME_BACKING_FILE_SIZE=$back_file_size
IMAGE_URLS=http://stackops.s3.amazonaws.com/images/centos-6.2-x86_64.img.tar.gz
EOF
./stack.sh

