#!/bin/bash
TOP_DIR=$(cd $(dirname "$0") && pwd)
if [[ $UID -ne 0 ]]; then
	echo "only root can execute this script"
	exit 1
fi

rm -f $TOP_DIR/devstack/stack-screenrc

if [ $# -ne 2 ];then
	echo "Usage:"
        echo "      `basename $0` -p password"
	exit 0
fi
while getopts 'p:' OPT; do
case $OPT in
        p)
            PASSWORD="$OPTARG";;
        ?)
            echo "Usage:"
            echo "      `basename $0` -p password"
	    exit 0
esac
done


#install captcha
cd $TOP_DIR
cd django-simple-captcha-0.3.0
sudo python setup.py install

#determine IP infor
cd $TOP_DIR
. devstack/functions
HOST_IP_IFACE=${HOST_IP_IFACE:-$(ip route | sed -n '/^default/{ s/.*dev \(\w\+\)\s\+.*/\1/; p; }')}
HOST_IP=""
HOST_IPS=`LC_ALL=C ip -f inet addr show ${HOST_IP_IFACE} | awk '/inet/ {split($2,parts,"/");  print parts[1]}'`
for IP in $HOST_IPS; do
        if ! (address_in_net $IP $FIXED_RANGE || address_in_net $IP $FLOATING_RANGE); then
            HOST_IP=$IP
            break;
        fi
done
if [ "$HOST_IP" == "" ]; then
    echo "Could not determine host ip address."
    exit 1
fi

#get available space
cd $TOP_DIR
size=$(sudo df -m|grep '/$'|awk '{print $4}')
back_file_size=$[size/1024]

#install openstack
FIXED_RANGE=10.0.0.0/20
FLOATING_RANGE=192.168.136.1/24
cd $TOP_DIR
cd devstack
sudo killall screen
cat <<EOF >localrc
FLAT_INTERFACE=eth0
FIXED_RANGE=$FIXED_RANGE
FIXED_NETWORK_SIZE=4096
FLOATING_RANGE=$FLOATING_RANGE
MULTI_HOST=1
MYSQL_PASSWORD=csdb123cnic
RABBIT_PASSWORD=$PASSWORD
SERVICE_PASSWORD=$PASSWORD
ADMIN_PASSWORD=$PASSWORD
SERVICE_TOKEN=$PASSWORD
ENABLED_SERVICES=g-api,g-reg,key,n-api,n-crt,n-obj,n-cpu,n-net,cinder,c-sch,c-api,c-vol,n-sch,n-novnc,n-xvnc,n-cauth,horizon,mysql,rabbit
VOLUME_BACKING_FILE_SIZE=$back_file_size
IMAGE_URLS=http://stackops.s3.amazonaws.com/images/centos-6.2-x86_64.img.tar.gz
EOF
./stack.sh

#install monitor related package and start services
cd $TOP_DIR
cd kanyun/
su -c "cat <<EOF >kanyun.conf
[server]
host: *
port: 5551

[mysql_db]
host:127.0.0.1
user:root
passwd:$PASSWORD
db:monitor
cache_server:localhost
cache_time_buffer:144000

[worker]
id: worker_$(hostname)
worker_timeout: 60
dataserver_host: 127.0.0.1
dataserver_port: 5551
log: /tmp/kanyun-worker.log
EOF" stack
sudo mysql -uroot -pcsdb123cnic -e 'DROP DATABASE IF EXISTS monitor;'
sudo mysql -uroot -pcsdb123cnic -e 'CREATE DATABASE monitor CHARACTER SET utf8;'
sudo mysql -uroot -pcsdb123cnic -e 'use monitor;source vm_monitor.sql;'
sudo ps ax|grep -v grep|grep kanyun-|awk '{print $1}'|xargs -L 1 kill -9 1>/dev/null 2>&1
sudo apt-get -y install libzmq-dev python-setuptools python-mysqldb redis-server python-redis python-zmq 1>/dev/null 2>&1
su -c "nohup ./kanyun-server > .kanyun-server.nohup 2>/dev/null&" stack
su -c "nohup ./kanyun-worker > .kanyun-worker.nohup 2>/dev/null&" stack

