#!/bin/bash

TOP_DIR=$(cd $(dirname "$0") && pwd)
cd django-simple-captcha-0.3.0
sudo python setup.py install

cd ../kanyun/
ps ax|grep -v grep|grep kanyun-|awk '{print $1}'|xargs -L 1 kill -9
apt-get -y install libzmq-dev python-setuptools python-mysqldb redis-server python-redis python-zmq
nohup ./kanyun-server > .kanyun-server.nohup&
nohup ./kanyun-worker >.kanyun-worker.nohup &
cd ..

cd devstack
sudo killall screen
cat <<EOF >localrc
FLAT_INTERFACE=eth0
FIXED_RANGE=10.0.0.0/20
FIXED_NETWORK_SIZE=4096
FLOATING_RANGE=192.168.136.192/26
MULTI_HOST=1
MYSQL_PASSWORD=csdb123cnic
RABBIT_PASSWORD=csdb123cnic
SERVICE_PASSWORD=csdb123cnic
ADMIN_PASSWORD=csdb123cnic
SERVICE_TOKEN=csdb123cnic
VOLUME_BACKING_FILE_SIZE=2048G
IMAGE_URLS=http://uec-images.ubuntu.com/precise/current/precise-server-cloudimg-amd64.tar.gz,http://stackops.s3.amazonaws.com/images/centos-6.2-x86_64.img.tar.gz
EOF

./stack.sh
