#!/bin/bash
TOP_DIR=$(cd $(dirname "$0") && pwd)
cd $TOP_DIR
cd kanyun/
sudo ps ax|grep -v grep|grep kanyun-|awk '{print $1}'|xargs -L 1 kill -9
nohup ./kanyun-worker >.kanyun-worker.nohup  2>/dev/null&

killall screen
cd $TOP_DIR
cd devstack
screen -dmS stack -c stack-screenrc
