#!/bin/bash
TOP_DIR=$(cd $(dirname "$0") && pwd)
TOP_DIR=$(cd $(dirname "$0") && pwd)
if [[ $UID -ne 0 ]]; then
        echo "only root can execute this script"
        exit 1
fi

cd $TOP_DIR
cd kanyun/
echo "ending monitoring services"
sudo ps ax|grep -v grep|grep kanyun-|awk '{print $1}'|xargs -L 1 kill -9
echo "starting monitoring services"
su -c "nohup ./kanyun-worker >.kanyun-worker.nohup  2>/dev/null&" stack

echo "restarting openstack services"
sudo killall screen
cd $TOP_DIR
cd devstack
if [ -f stack-screenrc ];then
	su -c "screen -dmS stack -c stack-screenrc&" stack
else
	echo "Found no devstack/stack-screenrc files"
	echo "ERROR!!!"
	exit 1
fi
echo "Done"

sudo service apache2 restart
